name: Deploy Frontend

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npm run build -- --configuration=production

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy frontend
        run: |
          rsync -avz --delete \
            --no-owner --no-group \
            dist/ deploy@${{ secrets.VPS_HOST }}:/var/www/maboutique/frontend

# name: "publish"

# on:
#   push:
#     branches:
#       - main
#     tags:
#       - "v*"

# jobs:
#   publish-tauri:
#     permissions:
#       contents: write
#     strategy:
#       fail-fast: false
#       matrix:
#         platform: [macos-latest, ubuntu-22.04, windows-latest]

#     runs-on: ${{ matrix.platform }}
#     steps:
#       - uses: actions/checkout@v4

#       - name: setup node
#         uses: actions/setup-node@v4
#         with:
#           node-version: 20

#       - name: install Rust stable
#         uses: dtolnay/rust-toolchain@stable

#       - name: install dependencies (ubuntu only)
#         if: matrix.platform == 'ubuntu-22.04'
#         run: |
#           sudo apt-get update
#           sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

#       - name: install frontend dependencies
#         run: npm install

#       - uses: tauri-apps/tauri-action@v0
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
#           releaseName: "Ma Boutique v__VERSION__"
#           releaseBody: "Boutique Management Application Build"
#           releaseDraft: true
#           prerelease: false

